/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface VnButton {
    'bold': string;
    'boxSize': string;
    /**
    * A test prop
    */
    'color': string;
    'href': string;
  }
  interface VnButtonAttributes extends StencilHTMLAttributes {
    'bold'?: string;
    'boxSize'?: string;
    /**
    * A test prop
    */
    'color'?: string;
    'href'?: string;
  }

  interface VnColorBlock {
    'bg': string;
    'p': string;
    'pl': string;
    'pt': string;
    'type': string;
  }
  interface VnColorBlockAttributes extends StencilHTMLAttributes {
    'bg'?: string;
    'p'?: string;
    'pl'?: string;
    'pt'?: string;
    'type'?: string;
  }

  interface VnContentLabel {
    'boxSize': string;
    /**
    * A test prop
    */
    'color': string;
  }
  interface VnContentLabelAttributes extends StencilHTMLAttributes {
    'boxSize'?: string;
    /**
    * A test prop
    */
    'color'?: string;
  }

  interface VnContentTitle {
    /**
    * A test prop
    */
    'test': string;
    'title': string;
  }
  interface VnContentTitleAttributes extends StencilHTMLAttributes {
    /**
    * A test prop
    */
    'test'?: string;
    'title'?: string;
  }

  interface VnLenker {
    'hasHover': string;
    'href': string;
    /**
    * A test prop
    */
    'text': string;
  }
  interface VnLenkerAttributes extends StencilHTMLAttributes {
    'hasHover'?: string;
    'href'?: string;
    /**
    * A test prop
    */
    'text': string;
  }

  interface VnSecondaryHeader {
    'color': string;
    'header': string;
    'test': string;
  }
  interface VnSecondaryHeaderAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'header': string;
    'test'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'VnButton': Components.VnButton;
    'VnColorBlock': Components.VnColorBlock;
    'VnContentLabel': Components.VnContentLabel;
    'VnContentTitle': Components.VnContentTitle;
    'VnLenker': Components.VnLenker;
    'VnSecondaryHeader': Components.VnSecondaryHeader;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'vn-button': Components.VnButtonAttributes;
    'vn-color-block': Components.VnColorBlockAttributes;
    'vn-content-label': Components.VnContentLabelAttributes;
    'vn-content-title': Components.VnContentTitleAttributes;
    'vn-lenker': Components.VnLenkerAttributes;
    'vn-secondary-header': Components.VnSecondaryHeaderAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLVnButtonElement extends Components.VnButton, HTMLStencilElement {}
  var HTMLVnButtonElement: {
    prototype: HTMLVnButtonElement;
    new (): HTMLVnButtonElement;
  };

  interface HTMLVnColorBlockElement extends Components.VnColorBlock, HTMLStencilElement {}
  var HTMLVnColorBlockElement: {
    prototype: HTMLVnColorBlockElement;
    new (): HTMLVnColorBlockElement;
  };

  interface HTMLVnContentLabelElement extends Components.VnContentLabel, HTMLStencilElement {}
  var HTMLVnContentLabelElement: {
    prototype: HTMLVnContentLabelElement;
    new (): HTMLVnContentLabelElement;
  };

  interface HTMLVnContentTitleElement extends Components.VnContentTitle, HTMLStencilElement {}
  var HTMLVnContentTitleElement: {
    prototype: HTMLVnContentTitleElement;
    new (): HTMLVnContentTitleElement;
  };

  interface HTMLVnLenkerElement extends Components.VnLenker, HTMLStencilElement {}
  var HTMLVnLenkerElement: {
    prototype: HTMLVnLenkerElement;
    new (): HTMLVnLenkerElement;
  };

  interface HTMLVnSecondaryHeaderElement extends Components.VnSecondaryHeader, HTMLStencilElement {}
  var HTMLVnSecondaryHeaderElement: {
    prototype: HTMLVnSecondaryHeaderElement;
    new (): HTMLVnSecondaryHeaderElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'vn-button': HTMLVnButtonElement
    'vn-color-block': HTMLVnColorBlockElement
    'vn-content-label': HTMLVnContentLabelElement
    'vn-content-title': HTMLVnContentTitleElement
    'vn-lenker': HTMLVnLenkerElement
    'vn-secondary-header': HTMLVnSecondaryHeaderElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'vn-button': HTMLVnButtonElement;
    'vn-color-block': HTMLVnColorBlockElement;
    'vn-content-label': HTMLVnContentLabelElement;
    'vn-content-title': HTMLVnContentTitleElement;
    'vn-lenker': HTMLVnLenkerElement;
    'vn-secondary-header': HTMLVnSecondaryHeaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
